"""add_blacklisted_tokens

Revision ID: 8ab4b6559839
Revises: ddfae8adf79b
Create Date: 2026-02-06 21:22:00.127704

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ab4b6559839'
down_revision: str | Sequence[str] | None = 'ddfae8adf79b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    schema_upgrades()
    data_upgrades()


def downgrade() -> None:
    data_downgrades()
    schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blacklisted_tokens',
        sa.Column(
            'token_jti',
            sa.String(length=255),
            nullable=False,
            comment='Уникальный идентификатор токена (JWT ID)',
        ),
        sa.Column(
            'user_id',
            sa.Integer(),
            nullable=False,
            comment='ID пользователя, которому был выдан токен',
        ),
        sa.Column('revoked_at', sa.DateTime(), nullable=False, comment='Время отзыва токена'),
        sa.Column(
            'expires_at',
            sa.DateTime(),
            nullable=False,
            comment='Время истечения токена (из JWT exp claim)',
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_blacklisted_tokens_expires_at', 'blacklisted_tokens', ['expires_at'], unique=False
    )
    op.create_index(
        op.f('ix_blacklisted_tokens_token_jti'), 'blacklisted_tokens', ['token_jti'], unique=True
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklisted_tokens_token_jti'), table_name='blacklisted_tokens')
    op.drop_index('idx_blacklisted_tokens_expires_at', table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###


VAL_1 = 'some_val'
VAL_2 = 'another_val'


def data_upgrades() -> None:
    """Optional data upgrades."""
    # op.execute(
    #         sa.text("""
    #         INSERT INTO <table_name> (<column_1>, <column_2>)
    #         VALUES (:val_1, :val_2)
    #         ON CONFLICT (<column_1>) DO NOTHING
    #     """).bindparams(val_1=VAL_1, val_2=VAL_2)
    # )
    pass


def data_downgrades() -> None:
    """Optional data downgrades."""
    # op.execute(
    #         sa.text("""
    #         DELETE FROM <table_name>
    #         WHERE <column_1> = :val_1 AND <column_2> = :val_2
    #     """).bindparams(val_1=VAL_1, val_2=VAL_2)
    # )
    pass
