"""create users table

Revision ID: 59be4b661082
Revises: 
Create Date: 2026-02-05 14:35:30.961303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59be4b661082'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    schema_upgrades()
    data_upgrades()


def downgrade() -> None:
    data_downgrades()
    schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


VAL_1 = 'some_val'
VAL_2 = 'another_val'


def data_upgrades() -> None:
    """Optional data upgrades."""
    # op.execute(
    #         sa.text("""
    #         INSERT INTO <table_name> (<column_1>, <column_2>)
    #         VALUES (:val_1, :val_2)
    #         ON CONFLICT (<column_1>) DO NOTHING
    #     """).bindparams(val_1=VAL_1, val_2=VAL_2)
    # )
    pass


def data_downgrades() -> None:
    """Optional data downgrades."""
    # op.execute(
    #         sa.text("""
    #         DELETE FROM <table_name>
    #         WHERE <column_1> = :val_1 AND <column_2> = :val_2
    #     """).bindparams(val_1=VAL_1, val_2=VAL_2)
    # )
    pass
